# Generated by Django 4.1.7 on 2023-02-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_useremail_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useremail',
            options={'verbose_name_plural': 'Email'},
        ),
        migrations.AlterField(
            model_name='useremail',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='email'),
        ),
    ]
