# Generated by Django 4.1.7 on 2023-02-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_useremail_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremail',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='email'),
        ),
    ]
