# Generated by Django 4.1.7 on 2023-02-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mailmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmessage',
            name='fifth_para',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='fourth_para',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='second_para',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='third_para',
            field=models.TextField(blank=True, null=True),
        ),
    ]
