# Generated by Django 4.1.7 on 2023-02-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_mailmessage_fifth_para_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
