# Generated by Django 4.1.7 on 2023-02-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_mailmessage_options_alter_useremail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmessage',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
